### ISSUE TITLE
Going to parent folder with keybinding doesn't update hints

### ISSUE THREAD

**Issue by CrafterKolyan** [mogelbrod/quick-opener#2]
Reproduction:
Ctrl+O
Ctrl+U

What I see:
Suggestions didn't change

What I expect:
Suggestions changed to the parent directory

Note:
If you go to parent directory with .. then it works correctly

**Comment by mogelbrod** [comment]
Thanks for the bug report! I can confirm that this appears to be broken - will investigate as soon as I find time to do so, hopefully within a week 👍
