### ISSUE TITLE
Root search path is not set to current workspace folder

### ISSUE THREAD

**Issue by emlautarom1** [mogelbrod/quick-opener#4]
To reproduce:

- Open an instance of VSCode without a folder (a "blank" workspace)
- Use "Quick Opener" to find a folder and click on "Add to Workspace". It also works with the default `File: Open Folder...` command
- Use "Quick Opener" and note how the "root" folder is not the current folder in the workspace but a different one (on Windows it points to `AppData\Roaming\Code\User`)

**Comment by mogelbrod** [comment]
Hey @emlautarom1! Thanks for creating these issues, I'll make sure to address them as soon as I have some time over 🙏 

QuickOpener should start off in the workspace folder by default if you have no open files. I just tried your repro on both a Windows and Mac OS machine and it appears to work as intended for me. Could you record a video of this happening?

**Comment by emlautarom1** [comment]
Hello and thanks for taking the time to take a look into this. It seems like it was my mistake: when I was opening the folder, the workspace associated with it had `settings.json` open making "Quick Opener" use the location of the file (`AppData\Roaming\Code\User`) rather than the root folder of the workspace.

Sorry to bother you with this issue and thanks for the amazing extension.
